#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$content = file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'composer.json');
$composer = json_decode($content,true);
$version = $composer['version'];
$name = $composer['displayName'];


$app = new Symfony\Component\Console\Application($name, $version);
$app->add(new Mosaiqo\SpaceStation\Console\ConfigCommand);
$app->add(new Mosaiqo\SpaceStation\Console\InitCommand);
$app->add(new Mosaiqo\SpaceStation\Console\StartCommand);
$app->add(new Mosaiqo\SpaceStation\Console\StopCommand);
$app->add(new Mosaiqo\SpaceStation\Console\RemoveCommand);
$app->add(new Mosaiqo\SpaceStation\Console\ClearCacheCommand);
$app->add(new Mosaiqo\SpaceStation\Console\GenerateSslCertificateCommand);
$app->run();